alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - component:
        name: html2png
      match:
        path:
          prefix: /
name: stubwizard-preview
region: nyc
services:
  - dockerfile_path: Dockerfile
#    environment_slug: go
    github:
      branch: master
      deploy_on_push: true
      repo: makraz/html2img
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: html2png
    source_dir: /
